# main text of home
name: Amey Tavkar
bio: I help startups build their MVP (Minimum Viable Product) and handle the technical side of things so that they can focus in on validating their awesome idea, start generating revenue and traction necessary for getting that huge funding from investors. 

# twitter summary info
description: A blog about startups, mobile development, user experience designing and stuff related.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/ameytavkar.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: https://ameytavkar.github.io/ameytavkar
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-103141942-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
  # categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: ameytavkar
twitter: ameytavkar
# google: mygoogle
instagram: ameytavkar
# pinterest: mypinterest
linkedin: ameytavkar
# youtube: myyoutube
# spotify: myspotify
github: ameytavkar
# lastfm: mylastfm
stackoverflow: 2902922/amey-tavkar
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
email: amey.tavkar@gmail.com

authors:
    ameytavkar:
        name: Amey Tavkar
        bio: Mobile Developer, Startup evangalist, Designer.
        external-image: false
        picture: assets/images/ameytavkar.jpg
        twitter: ameytavkar
    

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
